"""fix relation

Revision ID: 0991fd5883aa
Revises: 4296e46718d0
Create Date: 2023-11-19 14:58:09.334932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0991fd5883aa'
down_revision = '4296e46718d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order_detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order_item', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_order_session', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_items', ['id_order_item'], ['id_order_item'])
        batch_op.drop_column('id_session')

    # ### end Alembic commands ###
