"""fix fkk

Revision ID: 25cdaaeb4abd
Revises: 9bbd9eec2840
Create Date: 2023-11-14 20:08:53.613427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cdaaeb4abd'
down_revision = '9bbd9eec2840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_order_detail')

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order_item', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_oDetail_Oitem', 'order_items', ['id_order_item'], ['id_order_item'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_order_product', type_='foreignkey')
        batch_op.create_foreign_key('fk_order_product', 'product', ['id_product'], ['id_product'])
        batch_op.drop_column('id_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_order_product', type_='foreignkey')
        batch_op.create_foreign_key('fk_order_product', 'Product', ['id_product'], ['id_product'])
        batch_op.drop_column('quantity')

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_oDetail_Oitem', type_='foreignkey')
        batch_op.drop_column('id_order_item')

    # ### end Alembic commands ###
