"""add tables and relationship

Revision ID: 3083f65059be
Revises: 9d40a2a03502
Create Date: 2023-11-08 21:15:36.767869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3083f65059be'
down_revision = '9d40a2a03502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=100), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_payment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_payment'], ['payment_detail.id_payment'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('payment_detail',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['order_detail.id_order'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_table('order_items',
    sa.Column('id_order_item', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['order_detail.id_order'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_order_item')
    )
    op.create_table('reviews',
    sa.Column('id_reviews', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_reviews')
    )
    op.create_table('session',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_session')
    )
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.ForeignKeyConstraint(['id_session'], ['session.id_session'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('session')
    op.drop_table('reviews')
    op.drop_table('order_items')
    op.drop_table('payment_detail')
    op.drop_table('order_detail')
    # ### end Alembic commands ###
