"""update col

Revision ID: 389d447e0251
Revises: e5b5f2866c14
Create Date: 2023-11-14 13:16:20.367313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389d447e0251'
down_revision = 'e5b5f2866c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order_detail')
    op.drop_table('payment_detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'order_detail', ['id_order'], ['id_order'])

    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id_user'])

    op.drop_table('order_items')
    # ### end Alembic commands ###
