"""add payment date

Revision ID: 4296e46718d0
Revises: 636ee2468b8e
Create Date: 2023-11-18 05:10:27.955296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4296e46718d0'
down_revision = '636ee2468b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
