"""fix relationss

Revision ID: 5c955e073a6a
Revises: 0991fd5883aa
Create Date: 2023-11-19 15:08:13.084814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c955e073a6a'
down_revision = '0991fd5883aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=100), nullable=True),
    sa.Column('id_payment', sa.Integer(), nullable=True),
    sa.Column('id_session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_payment'], ['payment_detail.id_payment'], name='fk_oDetail_payment'),
    sa.ForeignKeyConstraint(['id_session'], ['session.id_session'], name='fk_oDetail_session'),
    sa.PrimaryKeyConstraint('id_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    # ### end Alembic commands ###
