"""recreate table

Revision ID: 7e7cc39431fb
Revises: 389d447e0251
Create Date: 2023-11-14 13:19:45.962336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7cc39431fb'
down_revision = '389d447e0251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_detail',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_table('order_detail',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=100), nullable=True),
    sa.Column('id_payment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_payment'], ['payment_detail.id_payment'], name='fk_oDetail_payment'),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('order_items',
    sa.Column('id_order_item', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['order_detail.id_order'], name='fk_order_Odetail'),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], name='fk_order_product'),
    sa.ForeignKeyConstraint(['id_session'], ['session.id_session'], name='fk_order_session'),
    sa.PrimaryKeyConstraint('id_order_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('order_detail')
    op.drop_table('payment_detail')
    # ### end Alembic commands ###
