"""tessss

Revision ID: 9bbd9eec2840
Revises: 8bee9a36160b
Create Date: 2023-11-14 20:02:31.367199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbd9eec2840'
down_revision = '8bee9a36160b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('tes')
        batch_op.create_foreign_key('fk_order_session', 'session', ['id_session'], ['id_session'])
        batch_op.create_foreign_key('fk_order_Odetail', 'Order_detail', ['id_order'], ['id_order'])
        batch_op.create_foreign_key('fk_order_product', 'Product', ['id_product'], ['id_product'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
