"""Change user column name

Revision ID: 9d40a2a03502
Revises: 9f173c9901e6
Create Date: 2023-11-08 21:09:39.622886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d40a2a03502'
down_revision = '9f173c9901e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id', new_column_name='id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_user', new_column_name='id')
    # ### end Alembic commands ###
