"""Change column name

Revision ID: 9f173c9901e6
Revises: e0f5b51411f3
Create Date: 2023-11-08 21:05:19.941687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f173c9901e6'
down_revision = 'e0f5b51411f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('product', 'id', new_column_name='id_product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'id_product', new_column_name='id')

    # ### end Alembic commands ###
