"""update table relationship

Revision ID: a995fd2df14f
Revises: d7e4cc6b03e3
Create Date: 2023-11-14 12:37:08.393416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a995fd2df14f'
down_revision = 'd7e4cc6b03e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_session', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_session', 'session', ['id_session'], ['id_session'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_session', type_='foreignkey')
        batch_op.drop_column('id_session')

    # ### end Alembic commands ###
