"""drop cart table

Revision ID: d7e4cc6b03e3
Revises: 3083f65059be
Create Date: 2023-11-14 12:32:48.009035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e4cc6b03e3'
down_revision = '3083f65059be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
        'cart',
        sa.Column('id_cart', sa.Integer(), nullable=False),
        sa.Column('id_session', sa.Integer(), nullable=True),
        sa.Column('id_product', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id_cart')
    )

    # ### end Alembic commands ###
