"""update column fk

Revision ID: e5b5f2866c14
Revises: a995fd2df14f
Create Date: 2023-11-14 13:00:09.238579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b5f2866c14'
down_revision = 'a995fd2df14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order_items')
    op.drop_table('Order_detail')
    op.drop_table('payment_detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cart',
        sa.Column('id_cart', sa.Integer(), nullable=False),
        sa.Column('id_session', sa.Integer(), nullable=True),
        sa.Column('id_product', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id_cart')
    )

    # ### end Alembic commands ###
