"""tes

Revision ID: fc759a371c4f
Revises: 7e7cc39431fb
Create Date: 2023-11-14 19:19:27.708048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc759a371c4f'
down_revision = '7e7cc39431fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methodsss', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.drop_column('payment_methodsss')

    # ### end Alembic commands ###
